name: Daily Commit

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Log
        run: |
          echo "Update: $(date)" >> progress_log.txt

      - name: Commit Changes
        run: |
          git config user.name "amosgaikwad"
          git config user.email "amosgaik16@gmail.com"

          git add progress_log.txt

          git diff --cached --quiet && exit 0

          git commit -m "Daily progress update"

          git push
